theme: jekyll-theme-minimal
title: Juan Ruiz Valencia
logo: https://avatars0.githubusercontent.com/u/19902389?s=400&v=4
description: This website is my portfolio containing projects I've completed or am currently working on.
