theme: jekyll-theme-minimal
title: Juan Ruiz Valencia
logo: https://avatars0.githubusercontent.com/u/19902389?s=400&v=4
description: I am a senior computer science major currently studying at Stephen F. Austin State University graduating in December, 2018. I have a passion for computer science and all things AI.
